### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by keyboardslammer** [fdibaldassarre/linux-shimeji#1]
Hi there, just wanted to thank you for updating and working on this!
I had a issue and I was wondering if anyone could help with this:
When I launch ./launch.sh I get the following:

Error: Could not find or load main class com.group_finity.mascot.Main
Caused by: java.lang.ClassNotFoundException: com.group_finity.mascot.Main

I tried going ahead and compiling it and the compiled version gives me this:

no main manifest attribute, in /home/sam/Games/linux-shimeji-master/target/linux-shimeji-0.0.1-SNAPSHOT-jar-with-dependencies.jar

I am using openjdk-11-jre-headless
Thank you for your time!

**Comment by fdibaldassarre** [comment]
Hi. My bad! I did not build the jar correctly. It should be fixed by 92856fc.
You can try pulling the changes and rebuilding the project or using the binaries in the [release page](https://github.com/fdibaldassarre/linux-shimeji/releases).

Thanks,
Francesco

**Comment by keyboardslammer** [comment]
Hi there, sorry for my late response.
It works great now! Thanks!
