### ISSUE TITLE
how do i get this to work on arch?

### ISSUE THREAD

**Issue by ximmunize** [fdibaldassarre/linux-shimeji#10]
hello!

i read a solved issue about getting this to work on arch, so i know it does work, but im looking for pointers on how to do it. im new to linux so im a little lost.

when i tried using dpkg, i get these issues:

> [🔴] × sudo dpkg -i linux-shimeji_0.0.1-4_all.deb
(Reading database ... 18 files and directories currently installed.)
Preparing to unpack linux-shimeji_0.0.1-4_all.deb ...
Unpacking linux-shimeji (0.0.1-4) over (0.0.1-4) ...
dpkg: dependency problems prevent configuration of linux-shimeji:
linux-shimeji depends on openjdk-11-jre; however:
Package openjdk-11-jre is not installed.
linux-shimeji depends on jarwrapper; however:
Package jarwrapper is not installed.

> dpkg: error processing package linux-shimeji (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing:
linux-shimeji

i used my package manager to download `jre11-openjdk`. when that didnt work i tried to instead use `jdk11-openjdk`, but that didnt work, either. installing both is a no go, as well since they are in conflict.

also, i dont know where to get jarwrapper. any help would be appreciated!

**Comment by fdibaldassarre** [comment]
Hi,
if you already have Java 11 installed (jre is fine) try to use this: [Executable only. deb](https://github.com/fdibaldassarre/linux-shimeji/releases/download/v0.0.1-b4/linux-shimeji_0.0.1-4_all_nodep.deb) . This package expects java 11 to be installed in `/usr/lib/jvm/java-11-openjdk-amd64`.

I don't use Arch so I am not sure on how to package stuff for it, I hope this works.

Cheers

**Comment by ximmunize** [comment]
hi again!

so i decided to install distrobox so i could install the package in ubuntu, but when i run it, i get the error `line 8: java: command not found`

when i tried to do it via dpkg, i got a whole lot of code vomit that repeats this over and over:

> java.lang.IllegalAccessException: class com.sun.jna.platform.WindowUtils$X11WindowUtils cannot access class sun.awt.X11GraphicsConfig (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @6328d34a
at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:398)
at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:709)
at java.base/java.lang.reflect.Method.invoke(Method.java:571)
at com.sun.jna.platform.WindowUtils$X11WindowUtils.getVisualID(WindowUtils.java:1629)
at com.sun.jna.platform.WindowUtils$X11WindowUtils.getAlphaCompatibleGraphicsConfiguration(WindowUtils.java:1650)
at com.sun.jna.platform.WindowUtils.getAlphaCompatibleGraphicsConfiguration(WindowUtils.java:1974)
at com.group_finity.mascot.x11.X11TranslucentWindow.<init>(X11TranslucentWindow.java:49)
at com.group_finity.mascot.x11.NativeFactoryImpl.newTransparentWindow(NativeFactoryImpl.java:31)
at com.group_finity.mascot.Mascot.<init>(Mascot.java:53)
at com.group_finity.mascot.Main.createMascot(Main.java:187)
at com.group_finity.mascot.Main.run(Main.java:71)
at com.group_finity.mascot.Main.main(Main.java:57)

however, i did see that java's path was `/usr/lib/jvm/java-11-openjdk`. I can't rename the folder or anything. any ideas?

**Comment by fdibaldassarre** [comment]
Hi, I can run the program using distrobox.
These are the steps I used
```
# Create container
distrobox create --name shimeji-test -i ubuntu:20.04 --additional-packages openjdk-11-jre
# Enter the container
distrobox enter shimeji-test
# Inside the container install the package
su -
cd /path/to/shimeji/deb
dpkg -i linux-shimeji_0.0.1-4_all_nodep.deb
```

After that I can execute the program with `distrobox enter shimeji-test -- linux-shimeji`

**Comment by ximmunize** [comment]
thank you so much! its working perfectly!
