### ISSUE TITLE
Doesn't work on linux mint cinnamon

### ISSUE THREAD

**Issue by ErFuyl** [fdibaldassarre/linux-shimeji#3]
opening the jar file only shows a black square on the taskbar, here is the output: https://pastebin.com/mdJQEpnK. 
.deb version doesn't give any output at all,

**Comment by fdibaldassarre** [comment]
Hi. Thanks for reporting this.

This error usually happens when using java > 11

Do you have Java 11 installed? If so you can change the launch.sh script to point to your Java 11 installation.

As an example, on Debian, the script is
```
export LD_LIBRARY_PATH="/usr/lib/jvm/default-java/lib/"
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -classpath target/linux-shimeji-0.0.1-SNAPSHOT-jar-with-dependencies.jar -Xmx1000m com.group_finity.mascot.Main
```

Let me know if it works.

Thanks

**Comment by ErFuyl** [comment]
> Hi. Thanks for reporting this.
> 
> This error usually happens when using java > 11
> 
> Do you have Java 11 installed? If so you can change the launch.sh script to point to your Java 11 installation.
> 
> As an example, on Debian, the script is
> 
> ```
> export LD_LIBRARY_PATH="/usr/lib/jvm/default-java/lib/"
> /usr/lib/jvm/java-11-openjdk-amd64/bin/java -classpath target/linux-shimeji-0.0.1-SNAPSHOT-jar-with-dependencies.jar -Xmx1000m com.group_finity.mascot.Main
> ```
> 
> Let me know if it works.
> 
> Thanks

My java version is 21.0.1 and i can't download older versions in their official website due needing registration.

**Comment by fdibaldassarre** [comment]
Hi,
you should be able to install openjdk-11 from the Linux Mint repo, or you can download the Linux binaries from the OpenJDK website without registering: https://jdk.java.net/java-se-ri/11-MR2

I plan to port this to a more recent Java version but as of now I don't have the time to do it...

**Comment by ErFuyl** [comment]
> Hi, you should be able to install openjdk-11 from the Linux Mint repo, or you can download the Linux binaries from the OpenJDK website without registering: https://jdk.java.net/java-se-ri/11-MR2
> 
> I plan to port this to a more recent Java version but as of now I don't have the time to do it...

The old 0.0.1-b3 version doesn't appear in neither in menu or when i search, so i ran from source and it is now working. still with some glitches.
