### ISSUE TITLE
I can't run the .deb for some reason

### ISSUE THREAD

**Issue by iDarknessSam** [fdibaldassarre/linux-shimeji#4]
when I try to run it it just say an error for me, here is the error:

```
[dark@LinuxPC linux-shimeji-master]$ ./linux-shimeji_0.0.1-3_all.deb 
./linux-shimeji_0.0.1-3_all.deb: line 1: syntax error near unexpected token `newline'
./linux-shimeji_0.0.1-3_all.deb: line 1: `!<arch>'
[dark@LinuxPC linux-shimeji-master]$ 
```

**Comment by fdibaldassarre** [comment]
Hi,
you need to install the package with
`sudo dpkg -i linux-shimeji_0.0.1-3_all.deb`

After the installation you can start it with
`linux-shimeji`
or by using the icon in Application.
