### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by MrDanikYT-pixel** [fdibaldassarre/linux-shimeji#5]
I don't understand how to run on arch linux
![screenshot-20240413-123513](https://github.com/fdibaldassarre/linux-shimeji/assets/83244543/acf59437-ef38-4a11-b792-da480584bc95)

**Comment by fdibaldassarre** [comment]
Hi,
you need to install the `maven` package and then build the project with
`mvn clean install`
This command creates a file named `linux-shimeji-0.0.1-SNAPSHOT-jar-with-dependencies.jar` in the folder `target`.

After building the project you can run it with the `launch.sh` script.

Note: use Java/OpenJDK 11

Thanks,
Francesco
